version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment: 
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
        - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
        - ./scripts:/home/oracle/setup/custom_scripts
  app:
    depends_on: 
        - mysqldb
    restart: unless-stopped
    build:
        context: .
    env_file: ./.env
    command: npm start
    volumes: 
        - .:/app/
        - ./app/node_modules
    ports:
        - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT

    environment: 
        MYSQL_HOST: mysqldb